config/routes.rb
Rails.application.routes.draw do

  root 'customers#new'
  resources:customers
  resources:products
  resources:categories

  get 'privates/login' => 'privates#login'
  post 'privates' => 'privates#doLogin'
  resources:privates

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, dependent: :destroy
	# accept nested attributetes for products field
	# if product name field on add new category form is empty
	# then never accept this nested features and just accept the category field only(default)
	accepts_nested_attributes_for :products, reject_if: lambda { |attr| attr[:pname].blank? }
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_secure_password
end

app/models/private.rb
class Private < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

	belongs_to :category
	#accepts_nested_attributes_for :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	# Prevent CSRF attacks by raising an exception.
  	# For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

  	def header_title ( title ) 
		@title = title
  	end

  	def isAdmin
  		@flag = true if session[:category] == "admin"
  	end

  	helper_method :isAdmin

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_filter :find_data, only: [ :edit, :destroy, :show, :update ]

  def index
  	@title = header_title( :"All categories" )
  	@categories = Category.all
  end

  def new
  	@title = header_title( :"Add New Category" )
  	@category = Category.new
    @category.products.build
  end

  def create
  	@category = Category.create ( permit_params )
  	if @category.save
  		redirect_to :action => 'index', notice: "Successfull Added Category"
  	else
  		render 'new'
  	end
  end

  def show
  end

  def edit
  end

  def update
  	if @category.update( permit_params )
  		redirect_to :action => 'index', notice: "Successfull Update Category"
  	else
  		render 'edit'
  	end  			
  end

  def destroy
  	if @category.destroy
  		redirect_to :action => "index", notice: "Successfull Delete Category"
  	else
  		render 'index'
  	end
  end

  def find_data
  	@category = Category.find( params[:id] )
  end

  private
  	def permit_params
  		params.require( :category ).permit( :cname, products_attributes: [:id, :pname, :pquantity, :pcolor, :pprice, :pno ] )
  	end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
  end

  def new
  	@title = header_title( :"Register Account" )
  	@customer = Customer.new
  end

  def create
  	@customer = Customer.create ( permit_params )
  	@msg = 1
  	if @customer.save && @customer.authenticate(params[:password])  		
  		respond_to do |format|
  			format.html { redirect_to :action => "new", notice: "SuccessFull Create Account"}
  			format.js
  		end
  	else
  		render 'new'


  	end
  end

  def show
  end

  def edit
  end

  def permit_params
  	allParams = :ic, :phone, :email, :address, :gender, :username, :password
  	params.require( :customer ).permit( allParams )
  end

end

app/controllers/privates_controller.rb
class PrivatesController < ApplicationController
  def index
  	@title = header_title( :"Admin Dashboard" )
  end

  def edit
  end

  def show
  end

  def new
  end

  def login
  	@title = header_title( :"Administrator Login" )
  end

  def doLogin
  	@admin = Private.where( 'username = ? and password = ?', params[:username], params[:password]).first
  	if @admin.present?
  		session[:category] = "admin"
  		session[:user_id] = @admin.id
  		redirect_to :action => 'index'
  	else
  		render 'login'
  	end

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :find_category,     only: [:create]
  before_action :find_product,      only: [:edit, :update, :destroy]
  before_action :getAllCategories,  only: [:new, :edit]

  def index
    @title   = header_title( :"All Products" )
    @products = Product.select("products.*, categories.cname").joins(:category)
  end
  
  def new
    @title   = header_title( :"Add New Product" )
    @cat     = Category.new
    @product = @cat.products.build
  end

  def create
    @product = @category.products.create( permit_params )
    if @product.save
      redirect_to :action => 'index', notice: "Successfull created product"
    else
      render 'new'
    end
  end

  def edit
    @title   = header_title( :"Edit Product" )
  end

  def update
    if @product.update( permit_params )
      redirect_to :action => 'index', notice: 'Successfull updated data'
    else
      render 'edit'
    end
  end

  def destroy
    if @product.destroy
      redirect_to :action => 'index', notice: 'Successfull deleted data'
    else
      render 'index'
    end
  end

  private

    def permit_params
      params.require(:product).permit(:pname, :pquantity, :pcolor, :pprice, :pno, :category_id)
    end
  
    def find_category
      @category = Category.find( params[:product][:category_id] )
    end

    def find_product
      @product = Product.find( params[:id] )
    end

    def getAllCategories
      # get all categories
      # to display on select html tag
      # in add new product page and
      # in edit new product page ( this share same form with add )
      @catAll  = Category.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/privates_helper.rb
module PrivatesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_categoryEditAdd.html.erb
<%= form_for @category do |f| %>
	<div class="panel panel-default">
		<div class="panel-heading">
			Category Form
		</div>
		<div class="panel-body">
			<div class="form-group">
			<%= f.label :cname, "Category Name", class: "control-label" %>
			<%= f.text_field :cname, class: "form-control" %>
			</div>
		</div>
	</div>
<!-- 	<div class="panel panel-default">
		<div class="panel-body">
			<%= f.submit  class: "pull-right" %>
		</div>
	</div> -->
	<div class="panel panel-default">
		<div class="panel-heading">
			Product Form (optional)
		</div>
		<%= f.fields_for :products do |ff| %>
		<div class="panel-body">
			<div class="form-group">
					<%= ff.label :pname, "Product Name" %>
					<%= ff.text_field :pname, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= ff.label :pquantity, "Product Quantity" %>
					<%= ff.text_field :pquantity, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= ff.label :pcolor, "Product Color" %>
					<%= ff.text_field :pcolor, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= ff.label :pprice, "Product Price" %>
					<%= ff.text_field :pprice, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= ff.label :pno, "Product Number" %>
					<%= ff.text_field :pno, class: "form-control" %>
				</div>				
		</div>
		<% end %>
	</div>
	<div class="panel panel-default">
		<div class="panel-body">
			<%= f.submit  class: "pull-right" %>
		</div>
	</div>
<% end %>

app/views/categories/edit.html.erb
<div class="row">
	<%= render 'categoryEditAdd' %>
</div>

app/views/categories/index.html.erb
<div class="row">
	<%= link_to "Add New Category", new_category_path, class: "btn btn-info" %>
</div>
<br/>
<div class="row">
	<table class="table table-striped">
		<tr>
			<th>No.</th>
			<th>Category Name</th>
			<th>Actions</th>
		</tr>
		<% 
		a = 0
		@categories.each do |d| %>
		<tr>
			<td><%= a+=1 %></td>
			<td><%= d.cname %></td>
			<td>
				<%= link_to "Edit", edit_category_path(d.id), class: "btn btn-primary" %>
				<%= link_to "Delete", category_path(d.id), 
					:data => { confirm: "Are you sure to do this??" },
					class: "btn btn-danger", method: 'delete' 
				%>
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/categories/new.html.erb
<div class="row">
	<%= render 'categoryEditAdd' %>
</div>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/customers/create.js.erb
<% if @msg.to_i == 1 %>
$('#msg').html('<%= @msg %>')
<% end %>

app/views/customers/edit.html.erb
<h1>Customers#edit</h1>
<p>Find me in app/views/customers/edit.html.erb</p>

app/views/customers/index.html.erb
<div class="row">
<div class="col-xs-2 col-sm-6 col-md-4 col-lg-2">
<div class="page-header"></div>
<h3>Customers#index</h3>
<p>Find me in app/views/customers/index.html.erb</p>
</div>
</div>

app/views/customers/new.html.erb
<div class="row">
	<div id="msg"></div>
	<div class="col-sm-12">
	<%= form_for @customer, html: { :class => "form-horizontal"} do |f| %>
	  	<div class="panel-group">
			<div class="panel panel-default">
				<div class="panel-heading">Personal Details</div>
				<div class="panel-body">					
					<div class="form-group">					
						<%= f.label :ic, "Identification Number", {:class => "col-sm-4 control-label"} %>
						<div class="col-sm-4">
							<%= f.text_field :ic,{:class => "form-control"} %>
						</div>
					</div>

					<div class="form-group">					
						<%= f.label :phone, "Phone Number", {:class => "col-sm-4 control-label"} %>
						<div class="col-sm-4">
							<%= f.text_field :phone,{:class => "form-control"} %>
						</div>
					</div>

					<div class="form-group">					
						<%= f.label :email, "Email", {:class => "col-sm-4 control-label"} %>
						<div class="col-sm-4">
							<%= f.text_field :email,{:class => "form-control"} %>
						</div>
					</div>

					<div class="form-group">					
						<%= f.label :address, "Current Address", {:class => "col-sm-4 control-label"} %>
						<div class="col-sm-4">
							<%= f.text_area :address,{:class => "form-control", :size => "15x5"} %>
						</div>
					</div>
					<div class="form-group">
						<%= f.label :gender, "Gender", {:class => "col-sm-4 control-label"} %>
						<div class="col-sm-4">
							<div class="radio">
								<label>
									<%= f.radio_button :gender,"Male" %> Male
								</label>
							</div>
							<div class="radio">
								<label>
									<%= f.radio_button :gender,"Female" %> Female
								</label>
							</div>
						</div>
					</div>

					
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					Authentication Information
				</div>
				<div class="panel-body">
					<div class="form-group">
						<%= f.label :username, { class: "col-sm-4 control-label"} %>
						<div class="col-sm-4">
							<%= f.text_field :username, { class: "form-control"} %>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :password, { class: "col-sm-4 control-label"} %>
						<div class="col-sm-4">
							<%= f.password_field :password, { class: "form-control"} %>
						</div>
					</div>

					<!-- <div class="form-group">
						<%= f.label :password_confirmation, { class: "col-sm-4 control-label"} %>
						<div class="col-sm-4">
							<%= f.password_field :password_confirmation, { class: "form-control"} %>
						</div>
					</div> -->
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-body">
					<%= f.submit "Create New Customer", { :class => "pull-right" } %>
				</div>
			</div>
	  	</div>
	<% end %>
	</div> 
</div>

app/views/customers/show.html.erb
<div class="page-header">
	<h1>Customers#show</h1>
</div>
<p>Find me in app/views/customers/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EComputer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNav" aria-expanded="false">
			<span class="sr-only">Toggle Navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
	<a class="navbar-brand">e-Computer</a>
	</div>

	<div class="collapse navbar-collapse" id="myNav">
		<% if isAdmin %>
		<ul class="nav navbar-nav">
			<li>
			<%= link_to "Home", root_path%>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Product Management <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li>
						<%= link_to "Add New Product", new_product_path %>
					</li>
					<li>
						<%= link_to "Display Products", products_path %>
					</li>
				</ul>
			</li>
		    <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Category Management <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li>
						<%= link_to "Add New Category", new_category_path %>
					</li>
					<li>
						<%= link_to "Display Categories", categories_path %>
					</li>
				</ul>
			</li>			
		</ul>
		<% else	%>
		<ul class="nav navbar-nav">
			<li>
			<%= link_to "Home", root_path%>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Dropdown <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><a>HDD</a></li>
					<li><a>CDROM</a></li>
				</ul>
			</li>
			<li>
				<%= link_to "Register Account", new_customer_path %>
			</li>
		</ul>
		<% end	%>
	</div>

</nav>
<div class="container">
	<div class="page-header">
		<h2><%= @title %></h2>
	</div>
	<%= yield %>
</div>

</body>
</html>

app/views/privates/edit.html.erb
<h1>Privates#edit</h1>
<p>Find me in app/views/privates/edit.html.erb</p>

app/views/privates/index.html.erb
<div class="row">
	<p>Please choose menus above</p>	
</div>

app/views/privates/login.html.erb
<div class="row">
<%= form_tag '/privates', method: 'post' do %>
	<div class="panel panel-default">
		<div class="panel-heading">
			Login Information
		</div>
		<div class="panel-body">
			<div class="form-group">
				<%= label_tag :username,"Username",{class: "control-label"} %>
				<%= text_field_tag :username,'', { :class => "form-control"} %>
			</div>
			<div class="form-group">
				<%= label_tag :password,"Password",{class: "control-label"} %>
				<%= password_field_tag :password,'', { :class => "form-control"} %>
			</div>			
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-body">
			<%= submit_tag "Login Now", { :class => "pull-right" } %>
		</div>
	</div>
<% end %>
</div>

app/views/privates/new.html.erb
<h1>Privates#new</h1>
<p>Find me in app/views/privates/new.html.erb</p>

app/views/privates/show.html.erb
<h1>Privates#show</h1>
<p>Find me in app/views/privates/show.html.erb</p>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
	<div class="panel panel-default">
		<div class="panel-heading">
			Product Form
		</div>
		<div class="panel-body">
			
				<div class="form-group">
					<%= f.label :pname, "Product Name" %>
					<%= f.text_field :pname, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :pquantity, "Product Quantity" %>
					<%= f.text_field :pquantity, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :pcolor, "Product Color" %>
					<%= f.text_field :pcolor, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :pprice, "Product Price" %>
					<%= f.text_field :pprice, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :pno, "Product Number" %>
					<%= f.text_field :pno, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :category_id, "Product Category" %>
					<%= f.select :category_id,@catAll.collect { |p| [p.cname, p.id] },{include_blank: true},class: "form-control" %>
				</div>
			
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-body">
		<%= f.submit class: "btn btn-primary pull-right"  %>
		</div>
	</div>
<% end %>

app/views/products/edit.html.erb
<div class="row">
 <%= render 'form' %>
</div>

app/views/products/index.html.erb
<div class="row">
<%= link_to "Add New Category", new_product_path, class: "btn btn-info" %>
</div>
<br/>
<div class="row">
	<table class="table table-striped">
	<tr>
		<th>No.</th>
		<th>Product Name</th>
		<th>Product Quantity</th>
		<th>Product Price</th>
		<th>Product Number</th>
		<th>Product Color</th>
		<th>Product Category</th>
		<th>Actions</th>
	</tr>
	<% 

	a = 0
	@products.each do |d| %>
	<tr>
		<td><%= a += 1 %></td>
		<td><%= d.pname %></td>
		<td><%= d.pquantity %></td>
		<td><%= d.pprice %></td>
		<td><%= d.pno %></td>
		<td><%= d.pcolor %></td>
		<td><%= d.cname %></td>
		<td>
			<%= link_to 'Edit', edit_product_path(d.id), class: "btn btn-primary" %>
			<%= link_to 'Delete', product_path(d.id), method: 'delete', class: "btn btn-danger", data: {confirm: 'Are you sure'} %>
		</td>
	</tr>
	<% end %>
	</table>
</div>

app/views/products/new.html.erb
<div class="row">
 <%= render 'form' %>
</div>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>